### PR TITLE
Add "MEMORY" StoreType

### PR DESCRIPTION
**Pull request by gbhrdt**
Added "MEMORY" StoreType (which is the default one), as it was missing.

### CODE REVIEW

**Comment by orefalo** [comment]
+1 I do need this option

**Comment by orefalo** [comment]
Opened in July ?!?! and still not merged in ? What do you need... a BEER? no better... a confinement !!!

Jokes appart
Plz merge in and release a new version. I use streaming in memory mode (with openfaas)

Tks

**Comment by wallyqs** [comment]
@orefalo ok just merged... though may want to check the helm charts instead for memory mode as well: https://github.com/nats-io/k8s#helm-charts-for-nats
They might be more flexible to use since the streaming operator was initially considered for clustered usage...

**Comment by orefalo** [comment]
arf!!
You just saved my day!
for some reasons https://github.com/nats-io/k8s#helm-charts-for-nats doesn't come out of google search.

anyway, spent two hours trying to rebuild the same. Thank you so much

**Pull request merged**
